version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_outputs:/app/outputs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend/web-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/web-ui:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start

volumes:
  backend_outputs: 